import 'package:get/get.dart';

class Translate extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          "Daily Tasks": "Daily Tasks",
          "Edit Profile": "Edit Profile",
          "Review Last Tasks": "Revie Last Tasks",
          "Premium Version": "Premium Version",
          "Premium Options": "Premium Options",
          "Purchase": "Purchase",
          "Categories": "Categories",
          "Add Category": "Add Category",
          "Done": "Done",
          "Review": "Review",
          "PremiumV": "Premium V.",
          "Buy Me A Coffee": "Buy me a coffee",
          "Settings": "Settings",
          "Invite Friends": "Invite Friends",
          "Contact Us": "Contact Us",
          "Add Name": "Add Name :",
          "Add Birthday Date": "Add Birthday Date :",
          "Add Phone Number": "Add Phone Number :",
          "Save": "Save",
          "Notifications": "Notifications",
          "Delete All Tasks": "Delete All Tasks",
          "Language": "Language",
          "Add Tasks": "Add Tasks",
          "Title": "Title",
          "Description": "description",
          "Attach An Image": "Attach an image",
          "Pick a Color": "Pick a Color",
          "Create Task": "Create Task",
          "Click the mic button to start recording...":
              "Click the mic button to start recording...",
          "recordeing...": "recordeing...",
          "English": "English",
          "Persian": "Persian",
          "Birthday List": "Birthday List",
          "Edit Name": "Edit Name :",
          "Edit Birthday Date": "Edit birthday date :",
          "Edit Phone Number": "Edit Phone Number :",
          "Edit the birthday items please!": "Edit the birthday items please!",
          "Nothing Added!": "Nothing added!",
          "Edit Category": "Edit Category",
          "Edit the task please!": "Edit the task please!",
          "CANCEL": "CANCEL",
          "SUBMIT": "SUBMIT",
          "You are not a permium contact": "You are not a permium contact",
          "check out this app...": "check out this app...",
          "Gallery": "Gallery",
          "Camera": "Camera",
          "Color picker": "Color picker",
          "Edit Task": "Edit Task",
          "Add Task": "Add Task",
          "Category": "Category",
          "Please select a category.": "Please select a category.",
          "There is no voice or title to create a task!":
              "There is no voice or title to create a task!",
          "There is no title or description to create a task!":
              "There is no title or description to create a task!",
          "Task Edited!": "Task Edited!",
          "Task Added successfully": "Task Added successfully",
          "Long press on each Task to see it's image":
              "Long press on each Task to see it's image",
          "Mon": "Mon",
          "Tue": "Tue",
          "Wed": "Wed",
          "Tur": "Tur",
          "Fri": "Fri",
          "Sat": "Sat",
          "Sun": "Sun",
          "Add a new Task!": "Add a new Task!",
          "Done?": "Done?",
          "Press Yes if you'he done this task.":
              "Press Yes if you'he done this task.",
          "Yes": "Yes",
          "No": "No",
          "Delete this Task?": "Delete this Task?",
          "Are you sure you want to delete this Task?":
              "Are you sure you want to delete this Task?",
          "Language Settings": "Language Settings",
          "reminder time :": "reminder time :",
          "Notification Settings": "Notification Settings",
          "Choose your best daily reminder :":
              "Choose your best daily reminder :",
          "Choose": "Choose",
          "Your best daily reminder :": "Your best daily reminder :",
          "Delete": "Delete",
          "Press Delete if you want to delete all the available tasks.":
              "Press Delete if you want to delete all the available tasks.",
          "Choose Task Date": "Choose Task Date"
        },
        'fa': {
          "Edit Profile": "ویرایش نمایه",
          "Daily Tasks": "وظایف روزانه",
          "Review Last Tasks": "مرور آخرین وظایف",
          "Premium Version": "نسخه پریمیوم",
          "Premium Options": "ویژگی های نسخه پریمیوم ",
          "Purchase": "پرداخت",
          "Categories": "دسته بندی ها",
          "Add Category": "افزودن دسته بندی",
          "Done": "انجام",
          "Review": "مرور وظایف قبلی",
          "PremiumV": "نسخه پریمیوم",
          "Buy Me a Coffee": "برای من قهوه بخر",
          "Settings": "تنظیمات",
          "Invite Friends": "دعوت از دوستان",
          "ContactUs": "تماس با ما",
          "Add Name": "اضافه کردن نام",
          "Add Birthday Date": "اضافه کردن تاریخ تولد",
          "Add Phone Number": "اضافه کردن شماره تلفن",
          "Save": "ذخیره",
          "Notifications": "اعلان ها",
          "Delete All Tasks": "حذف همه وظایف",
          "Language": "زبان",
          "Add Tasks": "وظایف را اضافه کنید",
          "Title": "عنوان",
          "Description": "توضیحات",
          "Attach An Image": "یک تصویر را ضمیمه کنید",
          "Pick a Color": "یک رنگ را انتخاب کنید",
          "Create Task": "ایجاد وظیفه",
          "Click The Buttons": "...برای شروع ضبط، روی دکمه میکروفون کلیک کنید",
          "recordeing": "ضبط کردندر حال",
          "English": "انگلیسی",
          "Persian": "فارسی",
          "Birthday List": "لیست تولد ها",
          "Edit Name": ": اضافه کردن اسم",
          "Edit Birthday Date": ": ویرایش تاریخ تولد",
          "Edit Phone Number": ": ویرایش شماره تماس",
          "Edit The Birthday Item": "!لطفا آیتم های تولد را ویرایش کنید",
          "Nothing Added": "!چیزی اضافه نشده",
          "Edit Category": "ویراش دسته بندی",
          "Edit The Task Please": "لطفا وظیفه را ویرایش کنید!",
          "Cancel": "لغو",
          "Sumbit": "تایید",
          "You Are Not a Premium Contact": "شما یک مخاطب پریمیوم نیستید",
          "Check Out This App": "...این برنامه را بررسی کنید",
          "Gallery": "گالری",
          "Camera": "دوربین",
          "Color Picker": "انتخاب رنگ",
          "Edit Task": "ویرایش وظیفه",
          "Add Task": "اضافه کردن وظیفه",
          "Category": "دسته بندی",
          "Please Select a Category": ".لطفا یک دسته بندی را انتخاب کنید",
          "There is no voice or title to create a task!":
              "!هیچ صدا یا عنوانی برای ایجاد یک وظیفه وجود ندارد",
          "There is no title or description to create a task!":
              "!هیچ عنوان یا توضیحی برای ایجاد یک وظیفه وجود ندارد",
          "Task Edited": "!وظیفه ویرایش شد",
          "Task Edited Successfully": "ویرایش وظیفه موفقیت آمیز بود",
          "Long Press To":
              "روی هر وظیفه طولانی فشار دهید تا تصویر آن را ببینید",
          "Mon": "دوشنبه",
          "Tue": "سه شنبه",
          "Wed": "چهارشنبه",
          "Tur": "پنجشنبه",
          "Fri": "جمعه",
          "Sat": "شنبه",
          "Sun": "یکشنبه",
          "Add a New Task": "!یک وظیفه جدید ایجاد کنید",
          "Done?": "انجام شد؟",
          "Press Yes if you'he done this task.":
              ".اگر این کار را انجام داده اید، بله را فشار دهید",
          "Yes": "بله",
          "No": "خیر",
          "Delete This Task": "این وظیفه پاک شود؟",
          "Are you sure you want to delete this Task?":
              "مطمئنی میخوای این وظیفه پاک بشه؟?",
          "Language Settings": "تنظیمات زبان",
          "Reminder Time": ": زمان یادآوری",
          "Notification Settings": "تنظیمات اعلان ها",
          "Choose your best daily reminder :":
              "بهترین یادآور روزانه خود را انتخاب کنید :",
          "Choose": "انتخاب",
          "Your Best Daily Reminder": ": بهترین زمان یادآوری روزانه شما",
          "Delete": "حذف",
          "Press Delete if you want to delete all the available tasks.":
              ".اگر می خواهید تمام وظایف موجود را حذف کنید، حذف را فشار دهید",
          "Choose Task Date": "تاریخ وظیفه را انتخاب کنید"
        }
      };
}
