import 'package:get/get.dart';

class Translate extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          "Daily Tasks": "Daily Tasks",
          "Edit Profile": "Edit Profile",
          "Review Last Tasks": "Revie Last Tasks",
          "Premium Version": "Premium Version",
          "Premium Options": "Premium Options",
          "Purchase": "Purchase",
          "Categories": "Categories",
          "Add Category": "Add Category",
          "Done": "Done",
          "Review": "Review",
          "Premium V.": "Premium V.",
          "Buy me A Coffee": "Buy me a coffee",
          "Settings": "Settings",
          "Invite Friends": "Invite Friends",
          "Contact Us": "Contact Us",
          "Add Name": "Add Name :",
          "Add Birthday Date": "Add Birthday Date :",
          "Add Phone Number": "Add Phone Number :",
          "Save": "Save",
          "Notifications": "Notifications",
          "Delete All Tasks": "Delete All Tasks",
          "Language": "Language",
          "Add Tasks": "Add Tasks",
          "title": "title",
          "description": "description",
          "Attach an Image": "Attach an image",
          "Pick a Color": "Pick a Color",
          "Create Task": "Create Task",
          "Click the mic button to start recording":
              "Click the mic button to start recording",
          "recording...": "recording...",
          "English": "English",
          "Persian": "Persian",
          "Birthday List": "Birthday List",
          "Edit Name": "Edit Name :",
          "Edit Birthday Date": "Edit birthday date :",
          "Edit Phone Number": "Edit Phone Number :",
          "Edit the birthday items please!": "Edit the birthday items please!",
          "Nothing Added!": "Nothing added!",
          "Edit Category": "Edit Category",
          "Edit the task please!": "Edit the task please!",
          "CANCEL": "CANCEL",
          "SUBMIT": "SUBMIT",
          "You are not a permium contact": "You are not a permium contact",
          "check out this app...": "check out this app...",
          "Gallery": "Gallery",
          "Camera": "Camera",
          "Color picker": "Color picker",
          "Edit Task": "Edit Task",
          "Add Task": "Add Task",
          "category": "category",
          "Please select a category.": "Please select a category.",
          "There is no voice or title to create a task!":
              "There is no voice or title to create a task!",
          "There is no title or description to create a task!":
              "There is no title or description to create a task!",
          "Task Edited!": "Task Edited!",
          "Task Added successfully": "Task Added successfully",
          "Long press on each Task to see it's image":
              "Long press on each Task to see it's image",
          "Mon": "Mon",
          "Tue": "Tue",
          "Wed": "Wed",
          "Tur": "Tur",
          "Fri": "Fri",
          "Sat": "Sat",
          "Sun": "Sun",
          "Add a new Task!": "Add a new Task!",
          "Done?": "Done?",
          "Press Yes if you'he done this task.":
              "Press Yes if you'he done this task.",
          "Yes": "Yes",
          "No": "No",
          "Delete this Task?": "Delete this Task?",
          "Are you sure you want to delete this Task?":
              "Are you sure you want to delete this Task?",
          "Language Settings": "Language Settings",
          "reminder time :": "reminder time :",
          "Notification Settings": "Notification Settings",
          "Choose your best daily reminder :":
              "Choose your best daily reminder :",
          "Choose": "Choose",
          "Your best daily reminder :": "Your best daily reminder :",
          "Delete": "Delete",
          "Press Delete if you want to delete all the available tasks.":
              "Press Delete if you want to delete all the available tasks.",
          "Choose Task Date": "Choose Task Date",
          'More Settings': 'More Settings',
          "error while emailing unclegenson@gmail.com":
              "error while emailing unclegenson@gmail.com",
          '''You must add your profile data to use the app
Your profile data will be unreachable for others.''':
              '''You must add your profile data to use the app
Your profile data will be unreachable for others.''',
          'Name :': 'Name :',
          'Number :': 'Number :',
          "Set Categories": "Set Categories",
          'Set Birthdays': 'Set Birthdays',
          'Set Language:': 'Set Language',
          'َApp Theme': 'App Theme',
          'SuccessFul': 'SuccessFul',
          'App Theme SuccessFully Updated': 'App Theme SuccessFully Updated',
          'Task Notifications': 'Task Notifications',
          "Reminder Birthday Dates": "Reminder Birthday Dates",
          'Task Image Selector': 'Task Image Selector',
          'Voice Tasks': 'Voice Tasks',
          'Daily Motivational Quotes': 'Daily Motivational Quotes',
          'Go Premium': 'Go Premium',
          'Premium Version Price': 'Premium Version Price',
          'for each month': 'for each month',
          'App Feedback': 'App Feedback',
          'subject=App Feedback&body=App Version 1.0:\n\nThe problem is ':
              'subject=App Feedback&body=App Version 1.0:\n\nThe problem is ',
          'Add New Task!': 'Add New Task!',
          'Task Notification will be in: ': 'Task Notification will be in: ',
          'Delete This Category': 'Delete This Category',
          'Are you sure you want to delete this Category?':
              'Are you sure you want to delete this Category?',
          'Choose best daily reminder time': 'Choose best daily reminder time',
          "Tap delete if you're sure you wanna delete all tasks":
              "Tap delete if you're sure you wanna delete all tasks",
          'delete': 'delete',
          'cancel': 'cancel',
          'Error!': 'Error!',
          'No Image Selected': 'No Image Selected',
          'We will let you know on': 'We will let you know on',
          'Check the fields and complete them.':
              'Check the fields and complete them.',
          'Click the mic button to start recording...':
              'Click the mic button to start recording...',
          'start': 'start',
          'end': 'end',
          'Good!': 'Good!',
          'Daily reminder set at': 'Daily reminder set at',
          'days': 'days',
          'hours': 'hours',
          'minutes': 'minutes',
          'from now!': 'from now!'
        },
        'fa': {
          'from now!': 'از الان',
          'minutes': 'دقیقه',
          'hours': 'ساعت',
          'days': 'روز',
          'Daily reminder set at': 'یادآور روزانه تنظیم شد',
          'Good!': 'موفقیت آموز بود!',
          "CANCEL": "لغو",
          "SUBMIT": "تایید",
          'start': 'شروع',
          'end': 'پایان',
          'Click the mic button to start recording...':
              'برای شروع ضبط صدا روی دکمه میکروفن کلیک کنید',
          'Check the fields and complete them.':
              'لطفا تمای فیلد ها را پر کنید.',
          'We will let you know on': 'را به شما اطلاع میدهیم',
          'No Image Selected': 'عکسی انتخاب نشد',
          'Error!': 'خطا!',
          'cancel': 'لغو',
          'delete': 'پاک شدن',
          "Tap delete if you're sure you wanna delete all tasks":
              "اگه میخوای کل وظایف پاک بشن روی پاک شدن کلیک کن",
          'Choose best daily reminder time':
              'بهترین زمان یادآور روزانه رو انتخاب کن',
          'Are you sure you want to delete this Category?':
              'مطمئنی میخوای این دسته بندی پاک بشه؟',
          'Delete This Category': 'پاک کردن این دسته بندی',
          'Task Notification will be in: ': ' یادآور این وظیفه در',
          'Add New Task!': 'یه وظیفه جدید اضافه کن!',
          'subject=App Feedback&body=App Version 1.0:\n\nThe problem is ':
              'subject=پیشنهاد برای آپدیت اپلیکیشن&body=ورژن 1.0:\n\n پیشنهاد من ',
          'App Feedback': 'پیشنهاد برای آپدیت اپلیکیشن:',
          'for each month': 'برای هر ماه',
          'Premium Version Price': 'قیمت نسخه پرمیوم',
          'Go Premium': 'نسخه پرمیموم',
          'Daily Motivational Quotes': 'جملات انگیزشی روزانه',
          'Voice Tasks': "وظیفه صوتی",
          'Task Image Selector': 'قابلیت انتخاب عکس برای هر وظیفه',
          "Reminder Birthday Dates": 'یادآور تاریخ های تولد',
          'Task Notifications': 'اعلان وظایف',
          "Edit Profile": "ویرایش نمایه",
          "Daily Tasks": "وظایف روزانه",
          "Review Last Tasks": "مرور آخرین وظایف",
          "Premium Version": "نسخه پریمیوم",
          "Premium Options": "ویژگی های نسخه پریمیوم ",
          "Purchase": "پرداخت",
          "Categories": "دسته بندی ها",
          "Add Category": "افزودن دسته بندی",
          "Done": "انجام",
          "Review": "مرور وظایف قبلی",
          "Premium V.": "نسخه پریمیوم",
          "Buy me a Coffee": "برای من قهوه بخر",
          "Settings": "تنظیمات",
          "Invite Friends": "دعوت از دوستان",
          "Contact Us": "تماس با ما",
          "Add Name": "نام",
          "Add Birthday Date": "تاریخ تولد",
          "Add Phone Number": "شماره تلفن",
          "Save": "ذخیره",
          "Notifications": "اعلان ها",
          "Delete All Tasks": "حذف همه وظایف",
          "Language": "زبان",
          "Add Tasks": "وظایف را اضافه کنید",
          "title": "عنوان",
          "description": "توضیحات",
          "Attach an Image": "یک تصویر را ضمیمه کنید",
          "Pick a Color": "یک رنگ را انتخاب کنید",
          "Create Task": "ایجاد وظیفه",
          "Click the mic button to start recording":
              "برای شروع ضبط، روی دکمه میکروفون کلیک کنید",
          "recording...": "در حال ضبط کردن صدا",
          "English": "انگلیسی",
          "Persian": "فارسی",
          "Birthday List": "لیست تولد ها",
          "Edit Name": ": اضافه کردن اسم",
          "Edit Birthday Date": ": ویرایش تاریخ تولد",
          "Edit Phone Number": ": ویرایش شماره تماس",
          "Edit The Birthday Item": "!لطفا آیتم های تولد را ویرایش کنید",
          "Nothing Added": "چیزی اضافه نشده",
          "Edit Category": "ویراش دسته بندی",
          "Edit The Task Please": "لطفا وظیفه را ویرایش کنید!",
          "Cancel": "لغو",
          "Sumbit": "تایید",
          "You Are Not a Premium Contact": "شما یک مخاطب پریمیوم نیستید",
          "Check Out This App": "این برنامه را بررسی کنید",
          "Gallery": "گالری",
          "Camera": "دوربین",
          "Color Picker": "انتخاب رنگ",
          "Edit Task": "ویرایش وظیفه",
          "Add Task": "اضافه کردن وظیفه",
          "category": "دسته بندی",
          "Please Select a Category": "لطفا یک دسته بندی را انتخاب کنید",
          "There is no voice or title to create a task!":
              "!هیچ صدا یا عنوانی برای ایجاد یک وظیفه وجود ندارد",
          "There is no title or description to create a task!":
              "!هیچ عنوان یا توضیحی برای ایجاد یک وظیفه وجود ندارد",
          "Task Edited": "!وظیفه ویرایش شد",
          "Task Edited Successfully": "ویرایش وظیفه موفقیت آمیز بود",
          "Long Press To":
              "روی هر وظیفه طولانی فشار دهید تا تصویر آن را ببینید",
          "Mon": "دوشنبه",
          "Tue": "سه شنبه",
          "Wed": "چهارشنبه",
          "Tur": "پنجشنبه",
          "Fri": "جمعه",
          "Sat": "شنبه",
          "Sun": "یکشنبه",
          "Add a New Task": "!یک وظیفه جدید ایجاد کنید",
          "Done?": "انجام شد؟",
          "Press Yes if you'he done this task.":
              "اگر این کار را انجام داده اید، بله را فشار دهید.",
          "Yes": "آره",
          "No": "نه",
          "Delete This Task": "این وظیفه پاک شود؟",
          "Are you sure you want to delete this Task?":
              "مطمئنی میخوای این وظیفه پاک بشه؟",
          "Language Settings": "تنظیمات زبان",
          "Reminder Time": ": زمان یادآوری",
          "Notification Settings": "تنظیم اعلان ها",
          "Choose your best daily reminder :":
              "بهترین یادآور روزانه خود را انتخاب کنید :",
          "Choose": "انتخاب",
          "Your best daily reminder :": "بهترین زمان یادآوری روزانه شما :",
          "Delete": "حذف",
          "Press Delete if you want to delete all the available tasks.":
              "اگر می خواهید تمام وظایف موجود را حذف کنید، حذف را فشار دهید.",
          "Choose Task Date": "تاریخ وظیفه را انتخاب کنید",
          "error while emailing unclegenson@gmail.com":
              "رخ داد unclegenson@gmail.com خطایی هنگام ایمیل به!",
          '''You must add your profile data to use the app
Your profile data will be unreachable for others.''':
              '''وارد کردن عکس نام و شماره تلفن الزامی است 
این اطلاعات کاملا خارج از دسترس دیگران است''',
          'Name :': 'نام :',
          'Number :': 'شماره تلفن : ',
          'More Settings': 'تنظیمات بیشتر',
          "Set Categories": "تنظیم دسته بندی ها",
          'Set Birthdays': "تنظیم تاریخ های تولد",
          'Set Language:': 'تنظیم زبان :',
          'App Theme': 'تم اپلیکیشن :',
          'SuccessFul': 'موفق بود',
          'App Theme SuccessFully Updated': 'تم اپلیکیشن با موفقیت تغییر کرد'
        }
      };
}
